### ISSUE TITLE
Covenant of Fire - Legion Champion

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy-bs2prep#11]

**Comment by capitaladot** [comment]
Implemented this in the 1.0 project; set total allowed as 3 and decremented by 2, then incremented by 1 when one of the allowed Consul types.

**Comment by Millicant** [comment]
Oh that's nice, I see.  I'll have to try that out - for some reason I was struggling with this one really hard.  There's quite a few that have the "only 1 except for X type Consul" restriction.

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#479

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#487
