### ISSUE TITLE
Theme: Army of Dark Compliance

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy-bs2prep#27]
Add lots of stuff...
- [ ] Possible to use both LA and Militia/cults
- [ ] Min 1 Praetor or Centurion
- [ ] No more LA units than Militia/cults
- [ ] No Discipline Master Cadre
- [ ] Warmasters Due rule
- [ ] Disposable rule

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#473
