### ISSUE TITLE
Age of Darkness FoC missing 4th Elite Slot, Lord of War slot.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy-bs2prep#3]
I don't want to make things crazy by implementing structural changes, so I thought I'd file this here.

**Comment by Millicant** [comment]
Okay, thanks!

Lords of War aren't in the regular AoD Force Org - they are in an extra Lords of War force org.  The elites I will fix though.

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#494
