### ISSUE TITLE
Shared armo(ur) entry group, allowing copy-pastable Armo(u)r Characteristic Modifiers

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy-bs2prep#35]
I've managed the implement this in the 1.x project, so it should be possible, here.
Basically, I see this as a means of keeping rosters from reporting contradictory information (i.e., paid points for Artificer, but roster reports 3+ save).

**Comment by Millicant** [comment]
I've actually done this already, the shared Entrygroup is just used as a storage space for all the various types of weapons and wargear.  

Ideally, there should be no copy/pasting and only links with modifiers to prevent version control issues.

**Comment by capitaladot** [comment]
My phrasing is bad. I really mean copying and pasting of links.

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#465
