### ISSUE TITLE
[Anon] Bug report: The Horus Heresy.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy-bs2prep#37]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Cannot ad force due to being unable to select force type

**Comment by capitaladot** [comment]
You're probably on the wrong repo. Anyway, you need to "Delete All Data".

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#463
