### ISSUE TITLE
Steal Codex: Chaos Daemons from the 40k repo nerds

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy-bs2prep#4]
I kid, I kid.

But seriously, no need to reinvent the wheel here.  Once that codex is 2.0 compliant, we'll just have to snag a copy and transfer all the nonsense over.  It's going to be a royal pain in the butt.

**Comment by capitaladot** [comment]
- [ ] Backport Samus
- [ ] Backport Cor'bax Utterblight

**Comment by capitaladot** [comment]
The above are done in 1.x and can be imported then copy pasted.

**Comment by Millicant** [comment]
Understood.  I'm going to wait a bit until I iron out all the Force Organization stuff, that way it prevents double work.  Thanks for doing it for 1.15!

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#493
