### ISSUE TITLE
LA:AOD Updates

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy-bs2prep#7]
Verify and update all the LA:AOD changes once I have the book in hand
- [ ] Command squads combi-weapon
- [x] Vet tactical squad new skills list
- [ ] Tech-Marine Servo-automata new weapons list
- [ ] Apothecary Jump pack and bike options
- [ ] Rapier squads weapons updates (thudd guns)
- [ ] Tarantula losing Fwd Deployment
- [ ] Dreadclaw Inertial Guidance
- [ ] Dreadclaws for Contemptor Dreadnoughts only?
- [ ] Javelins Strafing run
- [ ] Javelins special rule for close combat
- [ ] New Jetbike unit
- [ ] Deathstorm firing rule
- [ ] LR Achilles Thudd Gun ammo
- [ ] Achilles-Alpha ammo types
- [ ] Sicaran Venator 2nd pintle weapon
- [ ] Sicaran pintle weapon
- [ ] Deredeo weapon option (new)
- [ ] Whirlwind Scorpius pintle weapon
- [ ] Add Malcador
- [ ] Falchion weapon
- [ ] knights!? (separate issue)
- [ ] Command tanks?
- [ ] Orbital Assault update
- [ ] Pride of the Legion update
- [ ] Armoured breakthrough rules
- [ ] Pintle weapons options update
- [x] Veteran Combi-weapons

**Comment by Millicant** [comment]
Got the digital version.  Going over this now.

**Comment by capitaladot** [comment]
I'm basically finished (spare errors) with the old file, so snag what you can use there.

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#491
