### ISSUE TITLE
Stone Gauntlet - 1 Consul / Legion Champion

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy-bs2prep#8]
Only one allowed unless Legion Champion.  Not implemented.

**Comment by capitaladot** [comment]
Implemented this in the 1.0 project; set total allowed as 3 and decremented by 2, then incremented by 1 when one of the allowed Consul types.

**Comment by Millicant** [comment]
Nice idea.  I've been struggling with that for 2.0a.  I will try the same
thing and see if it works there.

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#490
